# Note: must set env var GITHUB_TOKEN for goreleaser
version: '1.0'
stages:
- test
- build
- release
steps:
  UnitTest:
    title: Run unit tests
    stage: test
    image: golang:1.13-alpine
    commands:
    - apk add git make bash file
    - make test
  BuildDockerImage:
    title: Build Docker image
    stage: build
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
  UploadReleaseArtifacts:
    title: Upload release artifacts
    stage: release
    image: goreleaser/goreleaser:v0.106.0
    commands:
    - git checkout tags/${{CF_BRANCH_TAG_NORMALIZED}}
    - goreleaser --rm-dist
  PushDockerImageTagged:
    title: Push Docker image (tag)
    stage: release
    type: push
    candidate: ${{BuildDockerImage}}
    image_name: orasbot/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    registry: dockerhub
